### ISSUE TITLE
Can't login by url from command prompt

### ISSUE THREAD

**Issue by Driveiei** [JP-SKE15/ProjectISP-Barcamp-management#23]
I followed the instructions for installing your app locally but when I head over on google chrome browser with this url ```http://127.0.0.1:3000/login``` and try to sign in with github. It saids:
```word
This domain (127.0.0.1) is not authorized to run this operation. 
Add it to the OAuth redirect domains list in the Firebase console 
-> Auth section -> Sign in method tab.  Dismiss
```
Why I can't follow command prompt url?

**Comment by TongThanaphon** [comment]
We did not add that domain (127.0.0.1) into the firebase. We recommend you use **http://localhost:3000/** to run on local.

**Comment by Driveiei** [comment]
Oh, Thanks for your solution.
