### ISSUE TITLE
Improve README

### ISSUE THREAD

**Issue by Driveiei** [JP-SKE15/ProjectISP-Barcamp-management#25]
**List of Improvements:**

1. Wrong spelling words: 
- ```dowload``` -> ```download```
- ```Itetarion plan``` -> ```Iteration plan```
- ```Member``` -> ```Team members``` or ```Members```

2. Wrong grammar:

```
Barcamp management is a web application for manage Barcamp event.
Make managing event conveniently than manual is the main focus for this application
``` 
to be like:
```
Barcamp management is a web application for managing Barcamp events, 
which makes managing event more convenient than manually doing it yourselfs.
```

3. Add full-stop(.) at the end of sentences.

**Comment by TongThanaphon** [comment]
Okay. We will improve it.
