### ISSUE TITLE
Same database with 2 accounts.

### ISSUE THREAD

**Issue by Driveiei** [JP-SKE15/ProjectISP-Barcamp-management#26]
I followed the instructions for installing your app locally but when I head over on google chrome browser with this url ```http://localhost:3000/``` and try to sign in 2 accounts with google. Then, I found a problem. 
I just add database only first account but database seems to be on another account. 

See the pictures below:
![image](https://user-images.githubusercontent.com/32285760/48495130-e5392780-e861-11e8-8374-dc47db0a3836.png)
![image](https://user-images.githubusercontent.com/32285760/48495237-1fa2c480-e862-11e8-81d0-d89af47b28ce.png)

**Comment by TongThanaphon** [comment]
All user can see all topics that add to database.

**Comment by Driveiei** [comment]
I really apologies for my misunderstanding how to use this application.
